/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c PicturePlayerInterface -p picture_player_interface.h:picture_player_interface.cpp picture_player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "picture_player_interface.h"

/*
 * Implementation of interface class PicturePlayerInterface
 */

PicturePlayerInterface::PicturePlayerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

PicturePlayerInterface::~PicturePlayerInterface()
{
}

