/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a picture_player_adapter picture_player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PICTURE_PLAYER_ADAPTER_H_1279181673
#define PICTURE_PLAYER_ADAPTER_H_1279181673

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.amlogic.player.PicturePlayerInterface
 */
class PicturePlayerInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.amlogic.player.PicturePlayerInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.amlogic.player.PicturePlayerInterface\" >\n"
"    <method name=\"setDesktop\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"w\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"h\" />\n"
"    </method>\n"
"    <method name=\"createScene\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"w\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"h\" />\n"
"    </method>\n"
"    <method name=\"createPicture\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"pictureURL\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"w\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"h\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"parameter\" />\n"
"    </method>\n"
"    <method name=\"displayScene\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"transitionName\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"args\" />\n"
"    </method>\n"
"    <method name=\"adjustDisplayScene\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"degree\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"scale_x\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"scale_y\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"center_x\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"center_y\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"parameter\" />\n"
"    </method>\n"
"    <method name=\"ScenceStatus\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PicturePlayerInterfaceAdaptor(QObject *parent);
    virtual ~PicturePlayerInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int ScenceStatus(int id);
    void adjustDisplayScene(int degree, int scale_x, int scale_y, int center_x, int center_y, const QString &parameter);
    void createPicture(int id, const QString &pictureURL, int x, int y, int w, int h, const QString &parameter);
    void createScene(int id, int x, int y, int w, int h);
    void displayScene(int id, const QString &transitionName, int args);
    void setDesktop(int w, int h);
Q_SIGNALS: // SIGNALS
};

#endif
