/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a picture_player_adapter picture_player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "picture_player_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PicturePlayerInterfaceAdaptor
 */

PicturePlayerInterfaceAdaptor::PicturePlayerInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PicturePlayerInterfaceAdaptor::~PicturePlayerInterfaceAdaptor()
{
    // destructor
}

int PicturePlayerInterfaceAdaptor::ScenceStatus(int id)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.ScenceStatus
    int status;
    QMetaObject::invokeMethod(parent(), "ScenceStatus", Q_RETURN_ARG(int, status), Q_ARG(int, id));
    return status;
}

void PicturePlayerInterfaceAdaptor::adjustDisplayScene(int degree, int scale_x, int scale_y, int center_x, int center_y, const QString &parameter)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.adjustDisplayScene
    QMetaObject::invokeMethod(parent(), "adjustDisplayScene", Q_ARG(int, degree), Q_ARG(int, scale_x), Q_ARG(int, scale_y), Q_ARG(int, center_x), Q_ARG(int, center_y), Q_ARG(QString, parameter));
}

void PicturePlayerInterfaceAdaptor::createPicture(int id, const QString &pictureURL, int x, int y, int w, int h, const QString &parameter)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.createPicture
    QMetaObject::invokeMethod(parent(), "createPicture", Q_ARG(int, id), Q_ARG(QString, pictureURL), Q_ARG(int, x), Q_ARG(int, y), Q_ARG(int, w), Q_ARG(int, h), Q_ARG(QString, parameter));
}

void PicturePlayerInterfaceAdaptor::createScene(int id, int x, int y, int w, int h)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.createScene
    QMetaObject::invokeMethod(parent(), "createScene", Q_ARG(int, id), Q_ARG(int, x), Q_ARG(int, y), Q_ARG(int, w), Q_ARG(int, h));
}

void PicturePlayerInterfaceAdaptor::displayScene(int id, const QString &transitionName, int args)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.displayScene
    QMetaObject::invokeMethod(parent(), "displayScene", Q_ARG(int, id), Q_ARG(QString, transitionName), Q_ARG(int, args));
}

void PicturePlayerInterfaceAdaptor::setDesktop(int w, int h)
{
    // handle method call com.amlogic.player.PicturePlayerInterface.setDesktop
    QMetaObject::invokeMethod(parent(), "setDesktop", Q_ARG(int, w), Q_ARG(int, h));
}

