	obj-y += player.o \
	player_ctrl.o \
	amutils_msg.o \
	player_av.o \
	player_es.o \
	player_ts.o \
	player_ps.o \
	player_rm.o \
	player_audio.o \
	player_video.o \
	player_para.o \
	player_hwdec.o \
	player_update.o\
	player_error.o\
	log_print.o \
	message.o \
	stream_decoder.o \
	thread_mgt.o 	\
	player_id.o \
	player_ffmpeg_ctrl.o \
	player_set_sys.o \
	h263vld.o \
	player_cache_file.o \
	player_cache_mgt.o \
	player_itemlist.o \
	player_sub.o \
	player_thumbnail.o \
	player_mate.o \
	version.o \

