all: 
	make -f Makefile.api dist
	make -f Makefile.api all
	
	#make -f Makefile.ctrl dist
	make -f Makefile.ctrl all
	
clean: 
	make -f Makefile.api clean
	make -f Makefile.ctrl clean
distclean: 
	make -f Makefile.api distclean
	make -f Makefile.ctrl distclean


