/*******************************************************************
 * 
 *  Copyright (C) 2007 by Sympeer, Inc. All Rights Reserved.
 *
 *  Description: the interface of ABoxBase error codes
 *
 *  Author: Sympeer Software
 *
 *******************************************************************/


#ifndef _XFER_ERROR_H_
#define _XFER_ERROR_H_


typedef enum {

	XFER_ERROR_OK = 0,

	XFER_ERROR_HTTP_STD_400 = 400, /* Bad Request */
	XFER_ERROR_HTTP_STD_401 = 401, /* Unauthorized */
	XFER_ERROR_HTTP_STD_402 = 402, /* Payment Required */
	XFER_ERROR_HTTP_STD_403 = 403, /* Forbidden */
	XFER_ERROR_HTTP_STD_404 = 404, /* Not Found */
	XFER_ERROR_HTTP_STD_405 = 405, /* Method Not Allowed */
	XFER_ERROR_HTTP_STD_406 = 406, /* Not Acceptable */
	XFER_ERROR_HTTP_STD_407 = 407, /* Proxy Authentication Required */
	XFER_ERROR_HTTP_STD_408 = 408, /* Request Timeout */
	XFER_ERROR_HTTP_STD_409 = 409, /* Conflict */
	XFER_ERROR_HTTP_STD_410 = 410, /* Gone */
	XFER_ERROR_HTTP_STD_411 = 411, /* Length Required */
	XFER_ERROR_HTTP_STD_412 = 412, /* Precondition Failed */
	XFER_ERROR_HTTP_STD_413 = 413, /* Request Entity Too Large */
	XFER_ERROR_HTTP_STD_414 = 414, /* Request-URI Too Long */
	XFER_ERROR_HTTP_STD_415 = 415, /* Unsupported Media Type */
	XFER_ERROR_HTTP_STD_416 = 416, /* Requested Range Not Satisfiable */
	XFER_ERROR_HTTP_STD_417 = 417, /* Expectation Failed */
	XFER_ERROR_HTTP_STD_500 = 500, /* Internal Server Error */
	XFER_ERROR_HTTP_STD_501 = 501, /* Not Implemented */
	XFER_ERROR_HTTP_STD_502 = 502, /* Bad Gateway */
	XFER_ERROR_HTTP_STD_503 = 503, /* Service Unavailable */
	XFER_ERROR_HTTP_STD_504 = 504, /* Gateway Timeout */
	XFER_ERROR_HTTP_STD_505 = 505, /* HTTP Version Not Supported */

	/* added by lbjiang BEGEIN */
	XFER_ERROR_STORAGE_SUCCESS = XFER_ERROR_OK,			/* success */
	XFER_ERROR_STORAGE_BEGIN = 1000,
	XFER_ERROR_STORAGE_IDLE = 1001,					/* thread idle */
	XFER_ERROR_STORAGE_IN_PROGRESS = 1002,			/* create file in progress... */
	XFER_ERROR_STORAGE_IN_PARAM_NULL = 1003,		/* function INCOMING param is null */
	XFER_ERROR_STORAGE_OPEN_FILE_FAIL = 1004,		/* open file error */
	XFER_ERROR_STORAGE_FILE_SEEK_FAIL = 1005,		/* seek file error */
	XFER_ERROR_STORAGE_FILE_WRITE_FAIL = 1006,		/* write file error */
	XFER_ERROR_STORAGE_FILE_EMPTY = 1007,			/* file is empty */
	XFER_ERROR_STORAGE_FILE_READ_ERR = 1008,		/* read file error */
	XFER_ERROR_STORAGE_CREATE_PATH_ERR = 1009,		/* make directory error */
	XFER_ERROR_STORAGE_CREATE_THREAD_ERR = 1010,	/* create thread error */
	XFER_ERROR_STORAGE_NO_CONTEXT = 1011,			/* there isn't context with current check_sum */
	XFER_ERROR_STORAGE_HAS_DOWNLOADED = 1012,		/* block has already downloaded */
    XFER_ERROR_STORAGE_MALLOC_FAILURE = 1013,		/* malloc memory failure */
	XFER_ERROR_STORAGE_TRIM_FAILURE = 1014,			/* trim memory failure */
	XFER_ERROR_STORAGE_MEM_BLOCK_ERR = 1015,		/* memory block error */
	XFER_ERROR_STORAGE_NO_DOWNLOADED = 1016,		/* block is not downloaded */
	XFER_ERROR_STORAGE_UNFINISHED_BLOCK = 1017,		/* block is unfinished */
	XFER_ERROR_STORAGE_PIECE_SHA1_ERR = 1018,		/* check piece sha1 return error, data error */
	XFER_ERROR_STORAGE_CREATE_MSGQ_ERR = 1019,		/* create MSG QUENE error */
	XFER_ERROR_STORAGE_REMOVED = 1020,				/* task was removed */

	
	XFER_ERROR_HTTP_SUCCESS = XFER_ERROR_OK,
	XFER_ERROR_HTTP_BEGIN = 1500,
	XFER_ERROR_HTTP_TODO = 1501,
	XFER_ERROR_HTTP_TASKID_ERR = 1502,
	XFER_ERROR_HTTP_OPEN_FILE_ERR = 1503,
	XFER_ERROR_HTTP_READ_FILE_ERR = 1504 ,
	XFER_ERROR_HTTP_SEEK_FILE_ERR = 1505 ,
	XFER_ERROR_HTTP_WRITE_FILE_ERR = 1506,
	XFER_ERROR_HTTP_DISK_NOT_ENOUGH =1507,
	XFER_ERROR_HTTP_IN_PARAM_NULL = 1508,
	XFER_ERROR_HTTP_CONTEXT_ERR = 1509 ,
	XFER_ERROR_HTTP_TIMER_INVALID = 1510 ,
	XFER_ERROR_HTTP_TIMEOUT = 1511,
	XFER_ERROR_HTTP_URL_ERR = 1512,
	XFER_ERROR_HTTP_CONNECT_ERR =  1513,
	XFER_ERROR_HTTP_CONNECT_CLOSED = 1514,
	XFER_ERROR_HTTP_REQUEST_ERR =1515 ,
	XFER_ERROR_HTTP_POST_START_ERR = 1516,
	XFER_ERROR_HTTP_POST_CHUNK_ERR = 1517,
	XFER_ERROR_HTTP_POST_DONE_ERR = 1518,
	XFER_ERROR_HTTP_DNS_CALL_ERR = 1519,
	XFER_ERROR_HTTP_DNS_RESULT_ERR =1520,
	XFER_ERROR_HTTP_MALLOC_FAILURE = 1521,
	XFER_ERROR_HTTP_TASK_EXIST = 1522,
	XFER_ERROR_HTTP_RESPONSE_NO_LENGTH = 1523,
	XFER_ERROR_HTTP_DATA_ERROR = 1524,
	XFER_ERROR_HTTP_CRYPT_ERROR = 1525,	
	XFER_ERROR_HTTP_REMOVED = 1526,
	XFER_ERROR_HTTP_STOP = 1527,
	XFER_ERROR_HTTP_FILE_CONTENT_ERROR = 1528,
	XFER_ERROR_HTTP_BUFF_OVERFLOW = 1529,
	XFER_ERROR_HTTP_UNINITIAL = 1530,
	XFER_ERROR_HTTP_WRITE_0BYTE_ERR = 1531,
	XFER_ERROR_HTTP_STATUS_ERROR = 1544,
	
	XFER_ERROR_THUNDER_BT_ERR = 1701,
	XFER_ERROR_THUNDER_DOWNLOADED = 1702,
	XFER_ERROR_THUNDER_BUSY = 1703,
	
	XFER_ERROR_TRANSFER_SUCCESS = XFER_ERROR_OK,
	XFER_ERROR_TRANSFER_BEGIN = 1900,
	XFER_ERROR_TASK_ADD_TYPE = 1901,
	XFER_ERROR_ADD_TYPE = 1902,
	XFER_ERROR_PAUSE_TASKID = 1903,
	XFER_ERROR_INFO_TASKID = 1904,
	XFER_ERROR_START_TASKID = 1905,
	XFER_ERROR_MALLOC_FAILURE = 1906,
	XFER_ERROR_NULL = 1907,
	XFER_ERROR_UNLOADED = 1908,
	XFER_ERROR_BEYOND_MAX_TASKS = 1909,
	/* added by lbjiang END */

	XFER_ERROR_NOTSUPPORT = 2000,
	XFER_ERROR_NOTINIT = 2001,
	XFER_ERROR_OUTOFMEMORY = 2300,
	XFER_ERROR_DNS_ERR = 2600,


	XFER_ERROR_FILENOTEXIST = 3000,
	XFER_ERROR_FAILOPENFILE = 3001,	
	XFER_ERROR_FAILREADFILE = 3002,
	XFER_ERROR_FAILWRITEFILE = 3003,

	XFER_ERROR_MOAP_XML_NO_DOWNLOAD = 4000,
	XFER_ERROR_MOAP_PARSE_XML_ERR = 4001 ,
	XFER_ERROR_MOAP_OPEN_XML_FILE_ERR = 4002 ,
	XFER_ERROR_MOAP_XML_FILE_NULL  = 4003,
	XFER_ERROR_MOAP_XML_FILE_STAT_ERR = 4004 ,
	XFER_ERROR_MOAP_XML_MALLOC_ERR = 4005 ,
	XFER_ERROR_MOAP_XML_READ_ERR = 4006,
	XFER_ERROR_MOAP_CREATE_PARSE_ERR = 4007 ,
	XFER_ERROR_MOAP_CREATE_TASK_ERR = 4008 ,
	XFER_ERROR_MOAP_CREATE_TASK_STARTED = 4009 ,
	XFER_ERROR_MOAP_TASK_MALLOC_ERR = 4010 ,
	XFER_ERROR_MOAP_NO_SEARCH_RESULT = 4011 ,
	XFER_ERROR_MOAP_SEARCH_ERR = 4012 ,
	XFER_ERROR_MOAP_LOGINING = 4013 ,
	XFER_ERROR_MOAP_REGISTER_FAILED =4014 ,

	 XFER_ERROR_MOAP_NOT_LAST_TASK = 4501 ,
	 XFER_ERROR_MOAP_XML_GET_FIRSTCHILD_ERR = 4502 ,
	 XFER_ERROR_MOAP_XML_GET_NODENAME_ERR = 4503 ,
	 XFER_ERROR_MOAP_NOT_ANY_PROGRAM = 4504 ,
	 XFER_ERROR_MOAP_SERVER_RETURN_ERROR = 4505 ,
	
	XFER_ERROR_MOAP_IPTIME_PARA_ERR = 4600 ,
	XFER_ERROR_MOAP_GET_NETCFG_ERR = 4601 ,

	XFER_ERROR_MOAP_SET_DES_KEY_ERR = 4700 ,
	XFER_ERROR_MOAP_NO_REGISTER = 4701 ,

	XFER_ERROR_SPBT_INIT_FAIL = 10000,
	XFER_ERROR_SPBT_MALLOC_ERROR = 10001,
	XFER_ERROR_SPBT_LOADTORRENT_ERROR = 10002,
	XFER_ERROR_SPBT_LOADTORRENT_2GLIMIT = 10003,
	XFER_ERROR_SPBT_CREATEFILELIST_ERROR = 10004,
	XFER_ERROR_SPBT_CREATEFILE_ERROR = 10005,
	XFER_ERROR_SPBT_WRITEFILE_ERROR = 10006,
	XFER_ERROR_SPBT_READFILE_ERROR = 10007,
	XFER_ERROR_SPBT_OVERMAXTASKCOUNT = 10008,   //
	XFER_ERROR_SPBT_NOTFOUNDTASK = 10009,       //not found task
	XFER_ERROR_SPBT_TASK_EXISTS = 10010,        //this torrentfile exists in task list
	XFER_ERROR_SPBT_UNSUPPORTED_ENCODING = 10011, //unsupported encoding	

	XFER_ERROR_HS_OK = 0 ,
	XFER_ERROR_RSS_PARSE_XML_ERR = 11001,
	XFER_ERROR_RSS_GET_XML_NODE_ERR = 11002,
	XFER_ERROR_HS_ADD_PARSE_MSG_ERR = 11004,
	XFER_ERROR_HS_FIND_PARSE_MSG_ERROR = 11005 ,
	XFER_ERROR_HS_CREATE_TASK_MALLOC_ERR = 11006 , 
	XFER_ERROR_HS_CREATE_TASK_ERR = 11007,
	XFER_ERROR_HS_OUT_TEXT_PARAM_ERROR = 11008 ,
	XFER_ERROR_HS_ADD_STOCK_ITEM_ERROR = 11009 ,
	XFER_ERROR_HS_DELETE_STOCK_NO_MENU = 11010 ,
	XFER_ERROR_HS_DETETE_STOCK_NO_POS = 11011 ,
	XFER_ERROR_HS_GET_MARKET_PIC_NO_TYPE = 11012 ,
	XFER_ERROR_HS_OWNER_STOCK_FILE_NO_EXIT = 11013 ,
	XFER_ERROR_HS_OPEN_OWNER_STOCK_FILE = 11014 ,
	XFER_ERROR_HS_MALLOC_MEMORY_FAILED = 11015,
	XFER_ERROR_HS_READ_OWNER_STOCK_FILE_ERROR = 11016 ,
	XFER_ERROR_HS_OWNER_STOCK_FILE_CHECK_ERROR = 11017 ,
	XFER_ERROR_HS_OWNER_STOCK_NO_NAME = 11018,
	XFER_ERROR_HS_CREATETIMER_FAILED = 11019,
	XFER_ERROR_HS_STOCK_TIMER_RUNED = 11020 ,
	XFER_ERROR_HS_STOCK_EXIST = 11021,
	XFER_ERROR_HS_DOWNLOADING_PIC = 11022,
	XFER_ERROR_HS_SEARCH_NO_STOCK = 11023,
	XFER_ERROR_HS_SEARCH_ERROR = 11024,
	XFER_ERROR_HS_NO_REGISTER = 11025 ,
	XFER_ERROR_HS_NO_LOGIN = 11026 ,
	XFER_ERROR_HS_SEARCH_NO_SONG = 11027,


	XFER_ERROR_AD_ALREADY_INITED = 12001,
	XFER_ERROR_AD_NOT_INITED = 12002,
	XFER_ERROR_AD_NOT_COMPLETE = 12003,
	XFER_ERROR_AD_NO_MEMORY = 12004,
	XFER_ERROR_AD_CREATE_MSG_Q_FAILED = 12005,
	XFER_ERROR_AD_POST_MSG_Q_FAILED = 12006,
	XFER_ERROR_AD_CREATE_SEM_FAILED = 12007,
	XFER_ERROR_AD_CREATE_TASK_FAILED = 12008,
	XFER_ERROR_AD_NO_SUCCESS_PIC = 12009,
	XFER_ERROR_AD_INVALID_PARAM = 12010,
	XFER_ERROR_AD_CAT_NOT_EXIST = 12011,
	XFER_ERROR_NO_PIC_TO_DOWN = 12012,
	XFER_ERROR_AD_DOWNLOADING = 12013,
	XFER_ERROR_AD_CAT_EXIST = 12014,

} xfer_errid_t;


#endif

