#!/bin/sh

# why does this fail ?
#[ -d /tmp/etc/network] || exit 0

if [ "X$1" = "Xstart" ]; then
  echo "S10move_network_interfaces: moving /etc/network"
  mkdir -p /tmp/etc/network
  cp -rf /etc/network /tmp/etc/
  mount -o bind /tmp/etc/network /etc/network
  #
  # make sure eth0 and wlan0 interfaces are up
  # xbmc will take care of actually configuring them
  # do it this way to keep from triggering
  # a lengthy dhcp probe at boot.
  echo "S10move_network_interfaces: ifconfig for eth0, wlan0"
  ifconfig eth0 up
  ifconfig wlan0 up
  echo "S10move_network_interfaces: done"
fi
