#!/bin/sh 

[ -d /mnt/userdata ] || exit 0

if [ "X$1" = "Xstart" ]; then
  echo "S10setup_userdata: mounting /mnt/userdata" 
  mkdir -p /mnt/userdata
  mount -t yaffs2 /dev/mtdblock4 /mnt/userdata
  echo "S10setup_userdata: binding /mnt/userdata/root,home" 
  mkdir -p /mnt/userdata/xios/root
  mount -o bind /mnt/userdata/xios/root /root
  mkdir -p /mnt/userdata/xios/home
  mount -o bind /mnt/userdata/xios/home /home
  echo "S10setup_userdata: done" 
fi 
