#! /bin/sh
#
case "$1" in
  start)
        echo "Starting mali..."
        /bin/echo 0 > /sys/class/graphics/fb0/blank
        /bin/echo 1 > /sys/class/graphics/fb1/blank
	/sbin/modprobe mali
	;;
  stop)
        echo "Stopping mali..."
        /sbin/modprobe -r mali
	;;
  restart|reload)
        echo "Restarting mali..."
        /sbin/modprobe -r mali
        /sbin/modprobe mali
	;;
  *)
  	;;
esac

exit $?
