/*******************************************************************
 * 
 *  Copyright (C) 2007 by Sympeer, Inc. All Rights Reserved.
 *
 *  Description: the interface of ABoxBase error codes
 *
 *  Author: Sympeer Software
 *
 *******************************************************************/


#ifndef _ABX_ERROR_H_
#define _ABX_ERROR_H_


typedef enum {
#ifndef _XFER_ERROR_H_COMM_
#define _XFER_ERROR_H_COMM_

	DLXML_ERROR_FILE_NOT_EXIST	= -110 ,
	DLXML_ERROR_NO_MEMORY = -109 ,
	DLXML_ERROR_OPEN_FAILED = -108 ,
	DLXML_ERROR_READ_FAILED = -107 ,
	DLXML_ERROR_NO_CHILD = -106 ,

	DLXML_ERROR_NO_MOVIELIST = -105 ,
	DLXML_ERROR_MOVIELIST_NO_CHILD = -104 ,
	DLXML_ERROR_NO_MEMORY_RCMD = -103 ,

	DLXML_ERROR_NO_SEARCHRESULT = -102 ,
	DLXML_ERROR_SEARCHRESULT_NO_CHILD  = -101 ,
	DLXML_ERROR_NO_MEMORY_SEARCH	= -100 ,
#endif
	ABXERR_MOAP_NO_MEM = -4 ,
	ABXERR_MOAP_GET_SERVER_ERR = -3 ,
	ABXERR_MOAP_HTTP_START_ERR = -2 ,
	ABXERR_MOAP_HTTP_ADD_ERR = -1 ,


        ABXERR_OK = 0,
        ABXERR_FAIL=-1,

	ABXERR_HTTP_STD_400 = 400, /* Bad Request */
	ABXERR_HTTP_STD_401 = 401, /* Unauthorized */
	ABXERR_HTTP_STD_402 = 402, /* Payment Required */
	ABXERR_HTTP_STD_403 = 403, /* Forbidden */
	ABXERR_HTTP_STD_404 = 404, /* Not Found */
	ABXERR_HTTP_STD_405 = 405, /* Method Not Allowed */
	ABXERR_HTTP_STD_406 = 406, /* Not Acceptable */
	ABXERR_HTTP_STD_407 = 407, /* Proxy Authentication Required */
	ABXERR_HTTP_STD_408 = 408, /* Request Timeout */
	ABXERR_HTTP_STD_409 = 409, /* Conflict */
	ABXERR_HTTP_STD_410 = 410, /* Gone */
	ABXERR_HTTP_STD_411 = 411, /* Length Required */
	ABXERR_HTTP_STD_412 = 412, /* Precondition Failed */
	ABXERR_HTTP_STD_413 = 413, /* Request Entity Too Large */
	ABXERR_HTTP_STD_414 = 414, /* Request-URI Too Long */
	ABXERR_HTTP_STD_415 = 415, /* Unsupported Media Type */
	ABXERR_HTTP_STD_416 = 416, /* Requested Range Not Satisfiable */
	ABXERR_HTTP_STD_417 = 417, /* Expectation Failed */
	ABXERR_HTTP_STD_500 = 500, /* Internal Server Error */
	ABXERR_HTTP_STD_501 = 501, /* Not Implemented */
	ABXERR_HTTP_STD_502 = 502, /* Bad Gateway */
	ABXERR_HTTP_STD_503 = 503, /* Service Unavailable */
	ABXERR_HTTP_STD_504 = 504, /* Gateway Timeout */
	ABXERR_HTTP_STD_505 = 505, /* HTTP Version Not Supported */

	/* added by lbjiang BEGEIN */
	ABXERR_STORAGE_SUCCESS = ABXERR_OK,			/* success */
	ABXERR_STORAGE_BEGIN = 1000,
	ABXERR_STORAGE_IDLE = 1001,					/* thread idle */
	ABXERR_STORAGE_IN_PROGRESS = 1002,			/* create file in progress... */
	ABXERR_STORAGE_IN_PARAM_NULL = 1003,		/* function INCOMING param is null */
	ABXERR_STORAGE_OPEN_FILE_FAIL = 1004,		/* open file error */
	ABXERR_STORAGE_FILE_SEEK_FAIL = 1005,		/* seek file error */
	ABXERR_STORAGE_FILE_WRITE_FAIL = 1006,		/* write file error */
	ABXERR_STORAGE_FILE_EMPTY = 1007,			/* file is empty */
	ABXERR_STORAGE_FILE_READ_ERR = 1008,		/* read file error */
	ABXERR_STORAGE_CREATE_PATH_ERR = 1009,		/* make directory error */
	ABXERR_STORAGE_CREATE_THREAD_ERR = 1010,	/* create thread error */
	ABXERR_STORAGE_NO_CONTEXT = 1011,			/* there isn't context with current check_sum */
	ABXERR_STORAGE_HAS_DOWNLOADED = 1012,		/* block has already downloaded */
    ABXERR_STORAGE_MALLOC_FAILURE = 1013,		/* malloc memory failure */
	ABXERR_STORAGE_TRIM_FAILURE = 1014,			/* trim memory failure */
	ABXERR_STORAGE_MEM_BLOCK_ERR = 1015,		/* memory block error */
	ABXERR_STORAGE_NO_DOWNLOADED = 1016,		/* block is not downloaded */
	ABXERR_STORAGE_UNFINISHED_BLOCK = 1017,		/* block is unfinished */
	ABXERR_STORAGE_PIECE_SHA1_ERR = 1018,		/* check piece sha1 return error, data error */
	ABXERR_STORAGE_CREATE_MSGQ_ERR = 1019,		/* create MSG QUENE error */
	ABXERR_STORAGE_REMOVED = 1020,				/* task was removed */

	
	ABXERR_HTTP_SUCCESS = ABXERR_OK,
	ABXERR_HTTP_BEGIN = 1500,
	ABXERR_HTTP_TODO = 1501,
	ABXERR_HTTP_TASKID_ERR = 1502,
	ABXERR_HTTP_OPEN_FILE_ERR = 1503,
	ABXERR_HTTP_READ_FILE_ERR = 1504 ,
	ABXERR_HTTP_SEEK_FILE_ERR = 1505 ,
	ABXERR_HTTP_WRITE_FILE_ERR = 1506,
	ABXERR_HTTP_DISK_NOT_ENOUGH =1507,
	ABXERR_HTTP_IN_PARAM_NULL = 1508,
	ABXERR_HTTP_CONTEXT_ERR = 1509 ,
	ABXERR_HTTP_TIMER_INVALID = 1510 ,
	ABXERR_HTTP_TIMEOUT = 1511,
	ABXERR_HTTP_URL_ERR = 1512,
	ABXERR_HTTP_CONNECT_ERR =  1513,
	ABXERR_HTTP_CONNECT_CLOSED = 1514,
	ABXERR_HTTP_REQUEST_ERR =1515 ,
	ABXERR_HTTP_POST_START_ERR = 1516,
	ABXERR_HTTP_POST_CHUNK_ERR = 1517,
	ABXERR_HTTP_POST_DONE_ERR = 1518,
	ABXERR_HTTP_DNS_CALL_ERR = 1519,
	ABXERR_HTTP_DNS_RESULT_ERR =1520,
	ABXERR_HTTP_MALLOC_FAILURE = 1521,
	ABXERR_HTTP_TASK_EXIST = 1522,
	ABXERR_HTTP_RESPONSE_NO_LENGTH = 1523,
	ABXERR_HTTP_DATA_ERROR = 1524,
	ABXERR_HTTP_CRYPT_ERROR = 1525,	
	ABXERR_HTTP_REMOVED = 1526,
	ABXERR_HTTP_STOP = 1527,
	ABXERR_HTTP_FILE_CONTENT_ERROR = 1528,
	ABXERR_HTTP_BUFF_OVERFLOW = 1529,
	ABXERR_HTTP_UNINITIAL = 1530,
	ABXERR_HTTP_WRITE_0BYTE_ERR = 1531,
	ABXERR_HTTP_STATUS_ERROR = 1544,
	
	ABXERR_THUNDER_BT_ERR = 1701,
	ABXERR_THUNDER_DOWNLOADED = 1702,
	
	ABXERR_TRANSFER_SUCCESS = ABXERR_OK,
	ABXERR_TRANSFER_BEGIN = 1900,
	ABXERR_TASK_ADD_TYPE = 1901,
	ABXERR_ADD_TYPE = 1902,
	ABXERR_PAUSE_TASKID = 1903,
	ABXERR_INFO_TASKID = 1904,
	ABXERR_START_TASKID = 1905,
	ABXERR_MALLOC_FAILURE = 1906,
	ABXERR_NULL = 1907,
	ABXERR_UNLOADED = 1908,
	ABXERR_BEYOND_MAX_TASKS = 1909,
	/* added by lbjiang END */

	ABXERR_NOTSUPPORT = 2000,
	ABXERR_NOTINIT = 2001,
	ABXERR_OUTOFMEMORY = 2300,
	ABXERR_DNS_ERR = 2600,


	ABXERR_FILENOTEXIST = 3000,
	ABXERR_FAILOPENFILE = 3001,	
	ABXERR_FAILREADFILE = 3002,
	ABXERR_FAILWRITEFILE = 3003,

	ABXERR_MOAP_XML_NO_DOWNLOAD = 4000,
	ABXERR_MOAP_PARSE_XML_ERR = 4001 ,
	ABXERR_MOAP_OPEN_XML_FILE_ERR = 4002 ,
	ABXERR_MOAP_XML_FILE_NULL  = 4003,
	ABXERR_MOAP_XML_FILE_STAT_ERR = 4004 ,
	ABXERR_MOAP_XML_MALLOC_ERR = 4005 ,
	ABXERR_MOAP_XML_READ_ERR = 4006,
	ABXERR_MOAP_CREATE_PARSE_ERR = 4007 ,
	ABXERR_MOAP_CREATE_TASK_ERR = 4008 ,
	ABXERR_MOAP_CREATE_TASK_STARTED = 4009 ,
	ABXERR_MOAP_TASK_MALLOC_ERR = 4010 ,
	ABXERR_MOAP_NO_SEARCH_RESULT = 4011 ,
	ABXERR_MOAP_SEARCH_ERR = 4012 ,
	ABXERR_MOAP_LOGINING = 4013 ,
	ABXERR_MOAP_REGISTER_FAILED =4014 ,

	 ABXERR_MOAP_NOT_LAST_TASK = 4501 ,
	 ABXERR_MOAP_XML_GET_FIRSTCHILD_ERR = 4502 ,
	 ABXERR_MOAP_XML_GET_NODENAME_ERR = 4503 ,
	 ABXERR_MOAP_NOT_ANY_PROGRAM = 4504 ,
	 ABXERR_MOAP_SERVER_RETURN_ERROR = 4505 ,
	
	ABXERR_MOAP_IPTIME_PARA_ERR = 4600 ,
	ABXERR_MOAP_GET_NETCFG_ERR = 4601 ,

	ABXERR_MOAP_SET_DES_KEY_ERR = 4700 ,
	ABXERR_MOAP_NO_REGISTER = 4701 ,

	ABXERR_SPBT_INIT_FAIL = 10000,
	ABXERR_SPBT_MALLOC_ERROR = 10001,
	ABXERR_SPBT_LOADTORRENT_ERROR = 10002,
	ABXERR_SPBT_LOADTORRENT_2GLIMIT = 10003,
	ABXERR_SPBT_CREATEFILELIST_ERROR = 10004,
	ABXERR_SPBT_CREATEFILE_ERROR = 10005,
	ABXERR_SPBT_WRITEFILE_ERROR = 10006,
	ABXERR_SPBT_READFILE_ERROR = 10007,
	ABXERR_SPBT_OVERMAXTASKCOUNT = 10008,   //
	ABXERR_SPBT_NOTFOUNDTASK = 10009,       //not found task
	ABXERR_SPBT_TASK_EXISTS = 10010,        //this torrentfile exists in task list
	ABXERR_SPBT_UNSUPPORTED_ENCODING = 10011, //unsupported encoding	

	ABXERR_HS_OK = 0 ,
	ABXERR_RSS_PARSE_XML_ERR = 11001,
	ABXERR_RSS_GET_XML_NODE_ERR = 11002,
	ABXERR_HS_ADD_PARSE_MSG_ERR = 11004,
	ABXERR_HS_FIND_PARSE_MSG_ERROR = 11005 ,
	ABXERR_HS_CREATE_TASK_MALLOC_ERR = 11006 , 
	ABXERR_HS_CREATE_TASK_ERR = 11007,
	ABXERR_HS_OUT_TEXT_PARAM_ERROR = 11008 ,
	ABXERR_HS_ADD_STOCK_ITEM_ERROR = 11009 ,
	ABXERR_HS_DELETE_STOCK_NO_MENU = 11010 ,
	ABXERR_HS_DETETE_STOCK_NO_POS = 11011 ,
	ABXERR_HS_GET_MARKET_PIC_NO_TYPE = 11012 ,
	ABXERR_HS_OWNER_STOCK_FILE_NO_EXIT = 11013 ,
	ABXERR_HS_OPEN_OWNER_STOCK_FILE = 11014 ,
	ABXERR_HS_MALLOC_MEMORY_FAILED = 11015,
	ABXERR_HS_READ_OWNER_STOCK_FILE_ERROR = 11016 ,
	ABXERR_HS_OWNER_STOCK_FILE_CHECK_ERROR = 11017 ,
	ABXERR_HS_OWNER_STOCK_NO_NAME = 11018,
	ABXERR_HS_CREATETIMER_FAILED = 11019,
	ABXERR_HS_STOCK_TIMER_RUNED = 11020 ,
	ABXERR_HS_STOCK_EXIST = 11021,
	ABXERR_HS_DOWNLOADING_PIC = 11022,
	ABXERR_HS_SEARCH_NO_STOCK = 11023,
	ABXERR_HS_SEARCH_ERROR = 11024,
	ABXERR_HS_NO_REGISTER = 11025 ,
	ABXERR_HS_NO_LOGIN = 11026 ,
	ABXERR_HS_SEARCH_NO_SONG = 11027,


	ABXERR_AD_ALREADY_INITED = 12001,
	ABXERR_AD_NOT_INITED = 12002,
	ABXERR_AD_NOT_COMPLETE = 12003,
	ABXERR_AD_NO_MEMORY = 12004,
	ABXERR_AD_CREATE_MSG_Q_FAILED = 12005,
	ABXERR_AD_POST_MSG_Q_FAILED = 12006,
	ABXERR_AD_CREATE_SEM_FAILED = 12007,
	ABXERR_AD_CREATE_TASK_FAILED = 12008,
	ABXERR_AD_NO_SUCCESS_PIC = 12009,
	ABXERR_AD_INVALID_PARAM = 12010,
	ABXERR_AD_CAT_NOT_EXIST = 12011,
	ABXERR_NO_PIC_TO_DOWN = 12012,
	ABXERR_AD_DOWNLOADING = 12013,
	ABXERR_AD_CAT_EXIST = 12014,

} abx_errid_t;



abx_errid_t abx_last_err();



#endif

