#!/bin/sh
exec 1>/tmp/init.log
exec 2>>/tmp/init.log

if [ "X$1" = "Xstart" ]; then
  # turn on 'power' led (right blue)
  if [ -f /sys/class/leds/Powerled/brightness ]; then
    echo 255 > /sys/class/leds/Powerled/brightness
  fi
  # turn off 'status' led (middle red)
  if [ -f /sys/class/leds/Statusled/brightness ]; then
    echo 0 > /sys/class/leds/Statusled/brightness
  fi
fi
